/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BranchDetailedInfo {
  name: string;
  isLocal: boolean;
  isRemote: boolean;
}

export interface CommitFileEntry {
  path: string;
  status: string;
  additions: number;
  deletions: number;
}

export interface DiffSummaryResult {
  files: Array<FileDiffSummaryItem>;
  total: number;
  truncated: boolean;
}

export interface FileDiffSummaryItem {
  path: string;
  status: string;
  staged: boolean;
}

export declare function getCommitBody(cwd: string, hash: string): Promise<string>;

export declare function getCommitFileDiff(
  cwd: string,
  hash: string,
  filePath: string,
): Promise<string>;

export declare function getCommitFiles(cwd: string, hash: string): Promise<Array<CommitFileEntry>>;

export declare function getCurrentBranch(cwd: string): Promise<string | null>;

export declare function getDefaultBranch(cwd: string): Promise<string | null>;

export declare function getDiffSummary(
  cwd: string,
  excludePatterns?: Array<string> | undefined | null,
  maxFiles?: number | undefined | null,
): Promise<DiffSummaryResult>;

/** Full-context diff (equivalent to git diff -U99999). Shows all lines of the file. */
export declare function getFullContextFileDiff(
  cwd: string,
  filePath: string,
  staged: boolean,
): Promise<string>;

export declare function getLog(
  cwd: string,
  limit?: number | undefined | null,
): Promise<Array<GitLogEntry>>;

export declare function getRemoteUrl(cwd: string): Promise<string | null>;

export declare function getSingleFileDiff(
  cwd: string,
  filePath: string,
  staged: boolean,
): Promise<string>;

export declare function getStatusSummary(
  worktreeCwd: string,
  baseBranch?: string | undefined | null,
  projectCwd?: string | undefined | null,
): Promise<GitStatusSummary>;

export declare function getUnpushedHashes(cwd: string): Promise<Array<string>>;

export interface GitLogEntry {
  hash: string;
  shortHash: string;
  author: string;
  relativeDate: string;
  message: string;
}

export interface GitStatusSummary {
  dirtyFileCount: number;
  unpushedCommitCount: number;
  unpulledCommitCount: number;
  hasRemoteBranch: boolean;
  isMergedIntoBase: boolean;
  linesAdded: number;
  linesDeleted: number;
}

export declare function listBranches(cwd: string): Promise<Array<string>>;

export declare function listBranchesDetailed(cwd: string): Promise<Array<BranchDetailedInfo>>;

/**
 * List every file in the repo: tracked from the index, plus untracked and
 * (optionally) `.gitignore`-ignored files from a worktree walk. Heavy build
 * directories (`node_modules`, `dist`, `.next`, …) are pruned regardless.
 *
 * Returns repository-relative paths with unix separators, deduplicated.
 */
export declare function listFiles(
  cwd: string,
  options?: ListFilesOptions | undefined | null,
): Promise<Array<string>>;

export interface ListFilesOptions {
  includeIgnored?: boolean;
}

/** Simple ping function to verify the native module loads correctly. */
export declare function ping(): string;

export declare function resetSoft(cwd: string): Promise<void>;
