// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process')
      .execSync('ldd --version', { encoding: 'utf8' })
      .includes('musl');
  } catch (e) {
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./native-git.win32-x64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        return require('@funny/native-git-win32-x64-msvc');
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`));
    }
  } else if (process.platform === 'darwin') {
    if (process.arch === 'arm64') {
      try {
        return require('./native-git.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        return require('@funny/native-git-darwin-arm64');
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`));
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        loadErrors.push(new Error('musl libc is not supported, only glibc'));
      } else {
        try {
          return require('./native-git.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          return require('@funny/native-git-linux-x64-gnu');
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`));
    }
  } else {
    loadErrors.push(
      new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`),
    );
  }
}

nativeBinding = requireNative();

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      },
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.getCurrentBranch = nativeBinding.getCurrentBranch;
module.exports.getDefaultBranch = nativeBinding.getDefaultBranch;
module.exports.getDiffSummary = nativeBinding.getDiffSummary;
module.exports.getLog = nativeBinding.getLog;
module.exports.getStatusSummary = nativeBinding.getStatusSummary;
module.exports.listBranches = nativeBinding.listBranches;
module.exports.ping = nativeBinding.ping;
