export {
  execute,
  executeSync,
  executeWithLogging,
  executeResult,
  executeShell,
  gitRead,
  gitWrite,
  SHELL,
  ProcessExecutionError,
  type ProcessResult,
  type ProcessOptions,
} from './process.js';

export { validatePath, validatePathSync, pathExists, sanitizePath } from './path-validation.js';

export { getNativeGit } from './native.js';

export {
  git,
  gitSync,
  gitSafeSync,
  isGitRepo,
  isGitRepoSync,
  getCurrentBranch,
  listBranches,
  listBranchesDetailed,
  fetchRemote,
  getDefaultBranch,
  getRemoteUrl,
  extractRepoName,
  initRepo,
  stageFiles,
  unstageFiles,
  revertFiles,
  addToGitignore,
  commit,
  runHookCommand,
  push,
  pull,
  createPR,
  mergeBranch,
  getDiff,
  getDiffSummary,
  getSingleFileDiff,
  getStatusSummary,
  invalidateStatusCache,
  deriveGitSyncState,
  getLog,
  getCommitBody,
  getCommitFiles,
  getCommitFileDiff,
  stash,
  stashPop,
  stashList,
  stashShow,
  resetSoft,
  cloneRepo,
  getUnpushedHashes,
  getFullContextFileDiff,
  type BranchInfo,
  type GitIdentityOptions,
  type GitStatusSummary,
  type GitLogEntry,
  type CommitFileEntry,
  type StashEntry,
} from './git.js';

export {
  createWorktree,
  listWorktrees,
  removeWorktree,
  removeBranch,
  getWorktreeBase,
  getWorktreeBasePath,
  getLastGitActivity,
  previewWorktree,
  WORKTREE_DIR_NAME,
  type WorktreeInfo,
  type WorktreePreview,
} from './worktree.js';

export { getWeaveStatus, ensureWeaveConfigured } from './weave.js';

export {
  fetchPRReviews,
  checkPRApprovalStatus,
  mergePR,
  getPRInfo,
  getPRDiff,
  postPRReview,
  getPRForBranch,
  type PRReview,
  type PRReviewComment,
  type ReviewDecision,
  type PRReviewData,
  type PRInfo,
  type ReviewEvent,
  type BranchPRInfo,
} from './github.js';
